environment:
    matrix:
      - CHANNEL: stable
        TARGET: x86_64-pc-windows-msvc
      - CHANNEL: stable
        TARGET: i686-pc-windows-msvc
      - CHANNEL: stable
        TARGET: x86_64-pc-windows-gnu
      - CHANNEL: stable
        TARGET: i686-pc-windows-gnu

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - git submodule update --init --recursive
  - set MINGW=C:/msys64/mingw64
  - set PATH=C:\Rust\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - rustc --version --verbose
  - cargo --version --verbose
  - make --version
  - if %TARGET:~-4%==-gnu x86_64-w64-mingw32-g++ --version

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
